name: Kronteq
version: '${project.version}'
main: com.github.ukraine1449.kronteq.Kronteq
authors: [ Ukraine1449 ]
website: plugins.world
commands:
  stats:
    description: used with just /stats or /stats (playername) to check either your own stats or another players stats
    permission-message: You do not have the permission to execute this command. Be an OP, or have permission; SUMO.stats
    permission: SUMO.stats
  joinqueue:
    description: A command to join the queue to fight someone random in the sumo arena
    permission-message: You do not have the permission to execute this command. Be an OP, or have permission; SUMO.joinQueue
    permission: SUMO.joinQueue
  getQueue:
    description: A command used to check how many players are in the queue
    permission-message: You do not have the permission to execute this command. Be an OP, or have permission; SUMO.getQueue
    permission: SUMO.getQueue
  leavequeue:
    description: A command to leave the queue to fight someone in the sumo arena. if you decide to rejoin the queue, you will be put in the back instead of the place where you left so be warned.
    permission-message: You do not have the permission to execute this command. Be an OP, or have permission; SUMO.leavequeue
    permission: SUMO.leavequeue
  duel:
    description: A command to duel someone else. To send a duel request do /duel (other players name) S, to accept do /duel (other players name) A, and to deny do /duel (other players name) D
    permission-message: You do not have the permission to execute this command. Be an OP, or have permission; SUMO.duel
    permission: SUMO.duel
  debug:
    description: A mysteryous command. No but seriously this just outputs all variables that are major in the main class
    permission-message: You do not have the permission to execute this command. Be an OP, or have permission; SUMO.debug
    permission: SUMO.debug