name: Kronteq
version: '${project.version}'
main: com.github.ukraine1449.kronteq.Kronteq
authors: [ Ukraine1449 ]
website: plugins.world
commands:
  stats:
    description: a command to get stats for a player
  joinqueue:
    description: a command to join the sumo que
  getQueue:
    description: a command to get to see the que.
  leavequeue:
    description: a command to leave the sumo queue
  duel:
    description: a command to request to duel someone. 